version: '3.7'

services:
  jwt_server:
    build: .
    ports:
      - "8000:8000"
    environment:
      SCRIPT_NAME: '/api/tc-tap'
      S3_IMAGERY_BUCKET_NAME: tc-tap-imagery
      S3_REGION_NAME: us-gov-west-1
      # S3_ACCESS_KEY: MUST BE SET IN env_file
      # S3_SECRET_KEY: MUST BE SET IN env_file
    env_file:
    - jwt_server.env
